import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Methodology — WebTaskBench",
  description:
    "How the WebTaskBench benchmark works, including HTML baseline, tokenization, and known limitations.",
};

export default function MethodologyPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16">
      <div className="mb-2 font-mono text-xs tracking-[0.25em] text-muted">
        METHODOLOGY
      </div>
      <h1 className="mb-8 font-display text-4xl font-bold">
        How We Measure
      </h1>

      <div className="space-y-8 font-body text-sm leading-relaxed text-muted">
        <section>
          <h2 className="mb-3 font-display text-xl font-bold text-text">
            Overview
          </h2>
          <p>
            WebTaskBench measures the token efficiency of SOM (Semantic Object
            Model) compared to raw HTML when fetching web pages for AI agents.
            The goal is to quantify how many tokens can be saved by using a
            structured, semantic representation instead of raw markup.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-bold text-text">
            HTML Baseline
          </h2>
          <p>
            The HTML baseline is captured using{" "}
            <code className="rounded bg-surface px-1.5 py-0.5 font-mono text-xs text-accent">
              curl -sL
            </code>
            , which follows redirects and fetches the raw HTTP response. This
            represents what an AI agent would receive if it simply fetched a page
            without a JavaScript-capable browser.
          </p>
          <p className="mt-3">
            This is intentionally a conservative baseline. Many AI agent tools
            use similar HTTP-only fetching. Browser-rendered pages would
            typically contain even more tokens due to dynamically inserted
            content, making the compression ratio potentially higher in practice.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-bold text-text">
            SOM Generation
          </h2>
          <p>
            SOM output is generated by Plasmate v0.3.0, which parses the HTML
            and produces a semantic object model. The SOM representation strips
            away presentational markup, scripts, styles, and other noise,
            retaining only the meaningful content and structure.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-bold text-text">
            Token Counting
          </h2>
          <p>
            All token counts use the{" "}
            <code className="rounded bg-surface px-1.5 py-0.5 font-mono text-xs text-accent">
              tiktoken cl100k_base
            </code>{" "}
            tokenizer, which is the encoding used by GPT-4 and GPT-4o. This
            provides a consistent and widely-understood metric for token
            consumption.
          </p>
          <p className="mt-3">
            Different models use different tokenizers, so actual token counts
            will vary slightly. However, the relative compression ratios should
            remain consistent across tokenizers.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-bold text-text">
            What &quot;Failure&quot; Means
          </h2>
          <p>
            A site is marked as &quot;failed&quot; when the curl-based fetch does
            not return usable HTML content. This typically happens due to:
          </p>
          <ul className="mt-3 list-none space-y-1 pl-4">
            <li className="before:mr-2 before:inline-block before:text-accent before:content-['▸']">
              Anti-bot detection (Cloudflare challenges, CAPTCHA walls)
            </li>
            <li className="before:mr-2 before:inline-block before:text-accent before:content-['▸']">
              JavaScript-only rendering (SPAs that return empty shells)
            </li>
            <li className="before:mr-2 before:inline-block before:text-accent before:content-['▸']">
              Server-side rate limiting or IP blocking
            </li>
            <li className="before:mr-2 before:inline-block before:text-accent before:content-['▸']">
              Cookie consent walls that block content
            </li>
          </ul>
          <p className="mt-3">
            7 out of 51 attempted sites failed in this benchmark run. These
            failures are documented transparently on the{" "}
            <a href="/failed" className="text-blue hover:text-accent transition-colors">
              Failed Sites
            </a>{" "}
            page.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-bold text-text">
            When SOM Is Larger
          </h2>
          <p>
            For 8 out of 44 sites, the SOM representation is actually larger
            than the raw HTML. This happens with minimal sites (like
            example.com, which is only 152 tokens of HTML) where the SOM
            overhead exceeds the content. For these sites, an agent would be
            better served by the raw HTML.
          </p>
          <p className="mt-3">
            This is expected and honest. SOM shines on complex, content-rich
            pages where there is significant markup overhead to strip away.
            Simple pages have little to compress.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-bold text-text">
            Known Limitations
          </h2>
          <ul className="list-none space-y-3 pl-4">
            <li className="before:mr-2 before:inline-block before:text-warning before:content-['▸']">
              <strong className="text-text">No JavaScript rendering:</strong>{" "}
              The curl baseline does not execute JavaScript. Sites that load
              content dynamically will show lower HTML token counts than what a
              browser would see.
            </li>
            <li className="before:mr-2 before:inline-block before:text-warning before:content-['▸']">
              <strong className="text-text">Single snapshot:</strong> Pages
              change over time. These results represent a single fetch on April
              1, 2026.
            </li>
            <li className="before:mr-2 before:inline-block before:text-warning before:content-['▸']">
              <strong className="text-text">Geographic variation:</strong>{" "}
              Content may vary by region. All fetches were made from a single
              Linux x86_64 server.
            </li>
            <li className="before:mr-2 before:inline-block before:text-warning before:content-['▸']">
              <strong className="text-text">Home pages only:</strong> Most URLs
              point to home pages or top-level docs. Sub-pages may have
              different characteristics.
            </li>
            <li className="before:mr-2 before:inline-block before:text-warning before:content-['▸']">
              <strong className="text-text">One tokenizer:</strong> Only
              cl100k_base is used. Other tokenizers may yield slightly different
              ratios.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-bold text-text">
            Benchmark Details
          </h2>
          <div className="overflow-x-auto rounded border border-border bg-surface-2">
            <table className="w-full font-mono text-xs">
              <tbody>
                {[
                  ["Plasmate version", "0.3.0"],
                  ["HTML baseline", "curl -sL (raw HTTP, no rendering)"],
                  ["Token counter", "tiktoken cl100k_base (GPT-4 tokenizer)"],
                  ["Date", "April 1, 2026"],
                  ["Platform", "Linux x86_64"],
                  ["Sites", "51 attempted, 44 successful, 7 failed"],
                  ["Source", "github.com/plasmate-labs/plasmate-benchmarks"],
                ].map(([key, val]) => (
                  <tr
                    key={key}
                    className="border-b border-border/40 last:border-0"
                  >
                    <td className="px-4 py-3 font-semibold uppercase tracking-wider text-muted">
                      {key}
                    </td>
                    <td className="px-4 py-3 text-text">{val}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-bold text-text">
            Reproduce This Benchmark
          </h2>
          <div className="rounded border border-border bg-surface p-4">
            <pre className="overflow-x-auto font-mono text-xs leading-relaxed text-accent">
              <code>{`git clone https://github.com/plasmate-labs/plasmate-benchmarks
cd plasmate-benchmarks
./run-benchmark.sh`}</code>
            </pre>
          </div>
        </section>
      </div>
    </div>
  );
}
